# Generated by Django 5.1 on 2024-09-03 23:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('contraseña', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(8)])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('nivel', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=50)),
            ],
        ),
    ]
